run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs: []
  skip-files: []
  modules-download-mode: readonly
  go: 1.22

linters-settings:
  gci:
    local-prefix: github.com/yitsushi/go-misskey
  goimports:
    local-prefix: github.com/yitsushi/go-misskey
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: false
    allow-unused: false
    require-explanation: true
    require-specific: false
  gocognit:
    min-complexity: 40
  varnamelen:
    ignore-names:
      - err
      - ok
      - wg
      - tc

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - exhaustruct
        - goconst
        - gocyclo
        - err113
        - gosec
        - lll
        - paralleltest
        - wastedassign
        - wrapcheck
        - funlen
    - text: "sig: func github.com/yitsushi/go-misskey/"
      linters:
      - wrapcheck
    - text: "sig: func \\(\\*?github.com/yitsushi/go-misskey/"
      linters:
      - wrapcheck

linters:
  enable-all: true
  disable:
    # Deprecated
    - exportloopref
    - gomnd
    - execinquery

    # Disabled for now
    - depguard
    - testableexamples
    - testifylint

    # We have no control over JSON keys in Misskey
    - tagliatelle
    
    # I don't agree with these
    - perfsprint

    # Mostly just annoying
    - exhaustruct
