name: pr-checker

on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          go get -u golang.org/x/lint/golint

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.28

      - name: go vet
        run: go vet ./...

      - name: go lint
        run: golint -set_exit_status ./...

      - name: go test
        run: go test -v -covermode=count -coverprofile=coverage.out ./...

      - name: Convert coverage.out to coverage.lcov
        uses: jandelgado/gcov2lcov-action@v1.0.7

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: coverage.lcov
